apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calibre-web
spec:
  rules:
  - host: books.faircloth.ca
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: calibre-web
            port: 
              number: 8083
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: calibre-web
spec:
  headers:
      customRequestHeaders:
        X-Script-Name: "/calibre"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: limit
spec:
  buffering:
    maxRequestBodyBytes: 20971520
