apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: calibre-web 
spec:
  replicas: 1
  serviceName: calibre-web
  selector:
    matchLabels:
      app: calibre-web
  template:
    metadata:
      name: calibre-web
      labels:
        app: calibre-web
    spec:
      containers:
      - name: calibre-web
        image: lscr.io/linuxserver/calibre-web:latest
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "America/Toronto"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        ports:
          - name: calibre-web
            containerPort: 8083
        volumeMounts:
        - mountPath: "/config"
          name: calibre-web-config
        - mountPath: "/books"
          name: calibre-library
      volumes:
      - name: calibre-web-config
        iscsi:
          targetPortal: 10.10.11.5:3260
          iqn: iqn.2000-01.com.synology:Library.calibre-web-config
          lun: 1
          fsType: ext4
          readOnly: false
      - name: calibre-library
        nfs:
          server: library.faircloth.ca
          path: /volume2/Calibre
