apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr 
spec:
  rules:
  - http:
      paths:
      - path: /sonarr
        backend:
          serviceName: sonarr 
          servicePort: 8989
