apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nzbget
spec:
  rules:
  - http:
      paths:
      - path: /nzbget
        backend:
          serviceName: nzbget
          servicePort: 6789
