apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr 
spec:
  rules:
  - http:
      paths:
      - path: /radarr
        backend:
          serviceName: radarr
          servicePort: 7878 
