apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: omada 
spec:
  rules:
  - host: omada.faircloth.ca
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: omada-manage
            port: 
              number: 8088
