apiVersion: v1
kind: Service
metadata:
  name: omada-tcp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: omada-0
  ports:
    - name: manage-http
      protocol: TCP
      port: 8088
      targetPort: 8088
    - name: manage-https
      protocol: TCP
      port: 8043
      targetPort: 8043
    - name: port-mngr-v1
      protocol: TCP
      port: 29811
      targetPort: 29811
    - name: port-adopt-v1
      protocol: TCP
      port: 29812
      targetPort: 29812
    - name: port-upg-v1
      protocol: TCP
      port: 29813
      targetPort: 29813
    - name: port-mngr-v2
      protocol: TCP
      port: 29814
      targetPort: 29814
---
apiVersion: v1
kind: Service
metadata:
  name: omada-udp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: omada-0
  ports:
    - name: port-app-disc
      protocol: UDP
      port: 27001
      targetPort: 27001
    - name: port-disc
      protocol: UDP
      port: 29810
      targetPort: 29810
