apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - --certificatesResolvers.le.acme.dnsChallenge=true
      - --certificatesResolvers.le.acme.dnsChallenge.provider=cloudflare
      - --certificatesresolvers.le.acme.email=admin@faircloth.ca
      - --certificatesresolvers.le.acme.storage=acme.json
      - --certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    env:
      - name: CF_API_EMAIL
        value: ryan@faircloth.ca
       - name: CF_API_KEY
         valueFrom:
           secretKeyRef:
             name: cloudflare-credentials
             key: cloudflareApiKey
