apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
spec:
  rules:
  - http:
      paths:
      - path: /plex
        pathType: ImplementationSpecific
        backend:
          name: plex
          port: 32400
