---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plex
resources:
  - namespace.yaml
  - statefulset.yaml  # ingress because service is nodeport
  - service.yaml
commonLabels:
  app: plex
