---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: dl
    name: plex-config
  iscsi:
    chapAuthSession: false
    targetPortal: 10.10.11.5:3260
    iqn: iqn.2000-01.com.synology:Library.plex-config
    lun: 1
    fsType: ext4
    readOnly: false
