all:
  children:
    server:
      hosts:
        rpi31.faircloth.ca
    agent:
      hosts:
        rpi32.faircloth.ca:
        rpi33.faircloth.ca:
        rpi41.faircloth.ca:
          taints:
            - plex=true:NoSchedule
            - plex=true:NoExecute
          labels:
            plex: "true"
        rpi42.faircloth.ca:
          labels:
            nzbget: "true"
