apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: organizr
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: organizr
          servicePort: 80
