apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: organizr
spec:
  rules:
  - host: media.faircloth.ca
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: organizr
            port:
              number: 80
