apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: organizr
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: organizr
          servicePort: 80
