---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nzbget-config-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: dl
    name: nzbget-config-pvc
  iscsi:
    chapAuthSession: false
    targetPortal: 10.10.11.5:3260
    iqn: iqn.2000-01.com.synology:Library.nzbget-config
    lun: 1
    fsType: ext4
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-config-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
