apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nzbget 
spec:
  replicas: 1
  serviceName: nzbget
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      name: nzbget
      labels:
        app: nzbget
    spec:
      containers:
      - name: nzbget
        image: lscr.io/linuxserver/nzbget:latest
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "America/Toronto"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        ports:
          - name: nzbget
            containerPort: 6789
        volumeMounts:
        - mountPath: "/config"
          name: nzbget-config
        - mountPath: "/downloads/completed"
          name: completed-downloads
      nodeSelector:
        nzbget: "true"
      volumes:
        - name: nzbget-config
          persistentVolumeClaim:
            claimName: nzbget-config-pvc
        - name: completed-downloads
          nfs:
            server: library.faircloth.ca
            path: /volume1/downloads/completed
      dnsConfig:
        options:
        - name: ndots
          value: "1"
